language: node_js
node_js:
  - "8.1.4"
before_install:
  - npm update -g npm
install:
  - npm install
  - gem install github_changelog_generator
script:
  - npm run lint
  - npm run build
# before_deploy:
#   # - github_changelog_generator
#   - git config user.name "warriorsword1989"
#   - git config user.email "linglong@navinfo.com"
#   - git add .
#   - git commit -m 'travis automatic generate changelog'
#   - git push origin master
#   - npm run build
#   - . build.sh
# deploy:
#   provider: releases
#   api_key: $GH_TOKEN
#   file: TollGate.zip
#   skip_cleanup: true
#   on:
#     tags: true
cache:
  directories:
  - node_modules
# notifications:
#   slack: navinfo:6troi7FBmywDvUc46jKuSJZE
